version: '3'
services:
   web:
       # Берем Dockerfile
       build: .
       container_name: django_users
       # Открываем порт на машине и перенаправляем на такой же порт в контейнере
       ports:
           - "8000:8000"
       volumes:
           - ./:/usr/src/app/
       command: python manage.py runserver 127.0.0.1:8000

       env_file:
           - .env.dev
       # Зависимость от сервиса Postgres
       depends_on:
           - db

   db:
       image: postgres
       container_name: postgres_django_users
       # Связывание тома с директорией в контейнере для сохранения данных postgres
       volumes:
           - pg_data:/var/lib/postgresql/data/
       ports:
           - "5432:5432"
       env_file:
           - .env.dev

volumes:
    pg_data: